# Generated by Django 4.2.7 on 2026-08-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_locationtrack_dailytourplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='distance_travelled',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='face_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='geo_fence_status',
            field=models.CharField(default='Inside', max_length=50),
        ),
        migrations.AddField(
            model_name='attendance',
            name='late_mark',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='travel_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='dealervisit',
            name='collection_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dealervisit',
            name='farmer_meeting_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dealervisit',
            name='next_follow_up',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealervisit',
            name='products_discussed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealervisit',
            name='voice_note',
            field=models.FileField(blank=True, null=True, upload_to='visit_voice_notes/'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Fuel', 'Fuel'), ('Food', 'Food'), ('Hotel', 'Hotel'), ('Travel', 'Travel'), ('Parking', 'Parking'), ('Misc', 'Misc'), ('Other', 'Other')], max_length=20),
        ),
    ]
