# Generated by Django 4.2.7 on 2026-08-22 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0004_attendance_distance_travelled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealervisit',
            name='customer_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dealervisit',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dealervisit',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dealervisit',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dealervisit',
            name='visit_purpose',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='dealervisit',
            name='visit_type',
            field=models.CharField(default='Distributor', max_length=50),
        ),
        migrations.AlterField(
            model_name='dealervisit',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
