# Generated by Django 4.2.7 on 2026-08-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_dealervisit_customer_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealervisit',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='visit_videos/'),
        ),
    ]
