# Generated by Django 4.2.7 on 2026-09-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_attendance_check_in_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='bus_train_car_fair',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='courier',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='ending_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Trip ending odometer KM', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='fair_auto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='fair_cab',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='food',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='internet_bill',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='km_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total KM * Applied KM Rate', max_digits=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='km_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Admin-assigned rate applied at claim submission time', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='laundry',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='local_conveyance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='other_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='other_vehicle_fair',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='phone_bill',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='photocopy',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='starting_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Trip starting odometer KM', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='total_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculated total KM (Ending - Starting)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Fuel', 'Fuel'), ('Food', 'Food'), ('Hotel', 'Hotel'), ('Travel', 'Travel'), ('Parking', 'Parking'), ('Misc', 'Misc'), ('Other', 'Other')], max_length=50),
        ),
    ]
