services:
  - type: web
    name: ccs-connect-backend
    env: python
    rootDir: backend
    buildCommand: "./build.sh"
    startCommand: "gunicorn ccs_backend.wsgi:application"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DJANGO_DEBUG
        value: "0"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "True"
