# Generated by Django 4.2.7 on 2026-08-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_lr_number_order_lr_receipt_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Pending Approval', 'Pending Approval'), ('Approved', 'Approved'), ('Packed', 'Packed'), ('Ready Dispatch', 'Ready Dispatch'), ('Loaded', 'Loaded'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Invoice Generated', 'Invoice Generated'), ('Payment Pending', 'Payment Pending'), ('Payment Complete', 'Payment Complete'), ('Cancelled', 'Cancelled'), ('Return', 'Return')], default='Draft', max_length=20),
        ),
    ]
