# Generated by Django 4.2.7 on 2026-08-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_bilty_date_order_bilty_number_order_bilty_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_terms',
            field=models.CharField(blank=True, default='Cash (15 Days)', max_length=100, null=True),
        ),
    ]
