# Generated by Django 4.2.7 on 2026-08-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_payment_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
