# Generated by Django 4.2.7 on 2026-08-02 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_product_barcode_product_hsn_code_product_packing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('scheme_type', models.CharField(choices=[('Buy X Get Y', 'Buy X Get Y'), ('Cash Discount', 'Cash Discount'), ('Target Bonus', 'Target Bonus')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('min_quantity', models.IntegerField(default=0)),
                ('free_quantity', models.IntegerField(default=0)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('target_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicable_to', models.ManyToManyField(blank=True, to='products.product')),
                ('dealer_specific', models.ManyToManyField(blank=True, limit_choices_to={'role': 'Dealer'}, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points', models.IntegerField()),
                ('source', models.CharField(help_text='Order ID or Scheme Name', max_length=255)),
                ('type', models.CharField(choices=[('Earned', 'Earned'), ('Redeemed', 'Redeemed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_points', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
