# Generated by Django 4.2.7 on 2026-08-01 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerprofile',
            name='assigned_distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_dealers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='ccs_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KYCProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kyc_status', models.CharField(choices=[('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('aadhaar_file', models.FileField(blank=True, null=True, upload_to='kyc/aadhaar/')),
                ('pan_file', models.FileField(blank=True, null=True, upload_to='kyc/pan/')),
                ('gst_file', models.FileField(blank=True, null=True, upload_to='kyc/gst/')),
                ('fertilizer_license', models.FileField(blank=True, null=True, upload_to='kyc/fertilizer/')),
                ('pesticide_license', models.FileField(blank=True, null=True, upload_to='kyc/pesticide/')),
                ('shop_photo', models.FileField(blank=True, null=True, upload_to='kyc/shop/')),
                ('profile_photo', models.FileField(blank=True, null=True, upload_to='profile_photos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
