# Generated by Django 4.2.7 on 2026-08-02 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_dealerprofile_assigned_distributor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributorprofile',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='distributorprofile',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Sales Manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_distributors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='distributorprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Super Admin', 'Super Admin'), ('Admin', 'Admin'), ('Distributor', 'Distributor'), ('Dealer', 'Dealer'), ('Employee', 'Employee'), ('Sales Manager', 'Sales Manager'), ('Accountant', 'Accountant'), ('Warehouse', 'Warehouse'), ('Support', 'Support')], default='Dealer', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Suspended', 'Suspended')], default='Pending', max_length=20),
        ),
    ]
