# Generated by Django 4.2.7 on 2026-08-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_distributorprofile_territory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerprofile',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='gps_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='land_area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='loyalty_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='outstanding_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='preferred_crop',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='preferred_products',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='distributorprofile',
            name='daily_sales_target',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='distributorprofile',
            name='distributor_area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='distributorprofile',
            name='has_warehouse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='distributorprofile',
            name='vehicles_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='employee_document',
            field=models.FileField(blank=True, null=True, upload_to='employee/documents/'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='leave_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='performance_score',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='sales_target',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
