# Generated by Django 4.2.7 on 2026-08-22 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_dealerprofile_credit_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributorprofile',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_distributors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Super Admin', 'Super Admin'), ('Admin', 'Admin'), ('Distributor', 'Distributor'), ('Dealer', 'Dealer')], default='Dealer', max_length=20),
        ),
    ]
