# Generated by Django 4.2.7 on 2026-09-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_distributorprofile_manager_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributorprofile',
            name='monthly_collection_plan',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='distributorprofile',
            name='monthly_sales_plan',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='monthly_collection_plan',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='monthly_sales_plan',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Super Admin', 'Super Admin'), ('Admin', 'Admin'), ('Distributor', 'Distributor'), ('Dealer', 'Dealer'), ('Warehouse', 'Warehouse')], default='Dealer', max_length=20),
        ),
    ]
