# Generated by Django 4.2.7 on 2026-09-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_distributorprofile_monthly_collection_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='km_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=5.0, help_text='Admin-controlled reimbursement rate per KM', max_digits=6, null=True),
        ),
    ]
